---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: marketingbot-ai-build
  namespace: janus-argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://gitlab-gitlab.apps.cluster-swr8d.swr8d.sandbox945.opentlc.com/development/marketingbot-gitops.git
    targetRevision: HEAD
    path: ./helm/ai
  destination:
    server: https://kubernetes.default.svc
    namespace: marketingbot-ai
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
